<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <RootNamespace>Taoliao.Core</RootNamespace>
    <LangVersion>5</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="4.5.3.3" />
  </ItemGroup>

</Project>
