<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net452</TargetFramework>
    <RootNamespace>Taoliao.CLI</RootNamespace>
    <LangVersion>5</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Taoliao.Core\Taoliao.Core.csproj" />
  </ItemGroup>

</Project>
